#!/bin/bash

echo raw2tec2D ${HOME}/Newmanv3.1/airdrop/Output/FTLEatt

./raw2tec2D ${HOME}/Newmanv3.1/airdrop/Output/FTLEatt

echo raw2tec2D ${HOME}/Newmanv3.1/airdrop/Output/FTLErep

./raw2tec2D ${HOME}/Newmanv3.1/airdrop/Output/FTLErep

echo raw2tec2D ${HOME}/Newmanv3.1/airdrop/Output/romsvelplot.raw

./raw2tec2D ${HOME}/Newmanv3.1/airdrop/Output/romsvelplot.raw

