#!/bin/bash

echo raw2tec3D ${HOME}/Newmanv3.1/LESSODAR/Output/FTLEatt

./raw2tec3D ${HOME}/Newmanv3.1/LESSODAR/Output/FTLEatt

echo raw2tec3D ${HOME}/Newmanv3.1/LESSODAR/Output/FTLErep

./raw2tec3D ${HOME}/Newmanv3.1/LESSODAR/Output/FTLErep

echo raw2tec3D ${HOME}/Newmanv3.1/LESSODAR/Output/romsvelplot.raw

./raw2tec3D ${HOME}/Newmanv3.1/LESSODAR/Output/romsvelplot.raw

echo raw2tec3D ${HOME}/Newmanv3.1/LESSODAR/Output/drift.raw

./raw2tec3D ${HOME}/Newmanv3.1/LESSODAR/Output/drift.raw